### PR TITLE
Historical metrics

### PR DESCRIPTION
**Pull request by cadamsdotcom**

### CODE REVIEW

**Comment by cadamsdotcom** [comment]
Looks like there's a bunch of broken-ness in the tests. But my code is covered and tests pass locally.

**Comment by ascandella** [comment]
Uh, I'm not super comfortable merging with broken tests. Can you describe why they're broken?

**Comment by ascandella** [comment]
Also coverage cannot decrease on this repo (says -5.8%, which is pretty bad).

**Comment by ascandella** [comment]
Can you add some context into the PR description describing what this PR accomplishes? All it says is "historical metrics" which doesn't tell me enough to review why this change should go in or what the code should be doing.

**Comment by cadamsdotcom** [comment]
This is to support fetching week-over-week coverage for rendering in slagen, an internal tool that generates reports on various metrics and which I'm enhancing in response to a push to make our tracking of various metrics more sophisticated, to automate work that some teams are already doing. Tracking code coverage as it changes week-over-week is desired by these teams, so adding the ability to query historical data which already exists in the uberalls DB seemed like a great approach.

**Comment by ascandella** [comment]
Sounds good. What's with the change from master -> origin/master?

**Comment by cadamsdotcom** [comment]
If you look in the database, phab has been populating it with origin/master so I figured that was a more sensible default value. With the previous value, you always had to include a "branch" parameter in your requests, which caused me several hours of painful debugging.

Here's the current state of the database inside Uber, with "master" v "origin/master":

```
mysql> select branch,count(*) from metrics where branch like '%master%' group by branch order by count(*) desc;
+-------------------------------------+----------+
| branch                              | count(*) |
+-------------------------------------+----------+
| origin/master                       |   241847 |
| master                              |     3513 |
| $GIT_SHA1/master                    |      515 |
| (elided)                            |        1 |
+-------------------------------------+----------+
4 rows in set (0.78 sec)

mysql> select branch,from_unixtime(max(timestamp)) from metrics where branch like '%master%' group by branch;
+-------------------------------------+-------------------------------+
| branch                              | from_unixtime(max(timestamp)) |
+-------------------------------------+-------------------------------+
| $GIT_SHA1/master                    | 2016-12-01 18:27:06           |
| master                              | 2015-01-28 06:50:14           |
| (elided)                            | 2016-10-27 20:56:27           |
| origin/master                       | 2016-12-02 03:27:46           |
+-------------------------------------+-------------------------------+
4 rows in set (0.65 sec)
```

**Comment by cadamsdotcom** [comment]
Also, since the last change coverage has remained the same, all checks now pass.

**Review by ascandella — APPROVED** [review]

**Comment by cadamsdotcom** [comment]
Thanks @sectioneight!

**Pull request merged**
